[tool.poetry]
name = "repl_python3_quadtreeexample"
version = "0.1.0"
description = ""
authors = ["rugbyprof <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pygame = "^2.1.2"
rich = "^12.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
